### ISSUE TITLE
Does not work for VSCode 1.56.1, OS: Darwin x64 20.3.0

### ISSUE THREAD

**Issue by mknycha-ingrid** [beerose/go-group-imports-vscode#11]
Hi, first of all thanks for this extension.
Unfortunately it does not work on my machine, it looks like there is no effect at all.
I have tried to:
1) Change the `go.formatTool`.
2) Run `Group imports` from the command palette of my IDE.

Could you please post a Visual Studio configuration for which it's working?
Here is my `settings.json`:
```
{
    "[go]": {
        "editor.insertSpaces": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false
    },
    "groupImports.onSave": true,
    "go.formatTool": "gofmt",
}
```
And here is the output of `About Visual Studio code`
```
Version: 1.56.1 (Universal)
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:24.325Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0
```

**Comment by beerose** [comment]
Hey @mknycha-ingrid,

It should work with those settings (I applied them on my machine, and it seemed to work). Maybe it has something to do with go modules support? Today I merged a PR fixing the extensions when used with go modules and released a new version. Let me know if it helped!

**Comment by mknycha-ingrid** [comment]
Yes, it looks like the issue was with my go env. Thanks for your response, I will close the issue.
