### ISSUE TITLE
Extension won't work with go modules aka "File is not in GOPATH"

### ISSUE THREAD

**Issue by AugustHell** [beerose/go-group-imports-vscode#5]
Working with go 1.11+ a package doesn't have to belong in the GOPATH.
It's now referenced in a go.mod file at package route level.
As this is the further way to program in go, checking for the gopath is error prone.
Would be nice if you can find a way out of that dilemma, maybe for checking for go.mod file in parent directories and reading the first line to define what's a package owned import.
Thanks for this nice extension.

**Comment by beerose** [comment]
Hi @AugustHell,
I'm super sorry for the delay. I've just fixed the issue and published new version of the extension.
