### ISSUE TITLE
"automatically group imports on save" conflict with vscode auto save

### ISSUE THREAD

**Issue by linyihai** [beerose/go-group-imports-vscode#9]
I configure my with code with config as below

![image](https://user-images.githubusercontent.com/18266718/86990022-43044b00-c1ce-11ea-8e3c-417bd15722cd.png)

![image](https://user-images.githubusercontent.com/18266718/86989475-1439a500-c1cd-11ea-9e00-16bfc41b11fe.png)

vscode will save constantly

This is my vscode version:

Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by beerose** [comment]
Hey @linyihai,

I wasn't able to reproduce it. I tried to apply the same settings and played with a few more options but it was working fine. Can you confirm that it's still happening?
